
package com.bbva.originacion.ws.oi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.bbva.originacion.parametros.ParametrosOriginacion;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* WSOriginacionIndividualService service = new WSOriginacionIndividualService();
* WSOriginacionIndividualSEI portType = service.getWSOriginacionIndividual();
* portType.creaExpedienteIdx(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "WSOriginacionIndividualService", targetNamespace = "http://oi.ws.bancomer.com", wsdlLocation = "http://150.50.102.88:16031/gestion/services/WSOriginacionIndividual?wsdl")
public class WSOriginacionIndividualService extends Service {

	private final static URL WSORIGINACIONINDIVIDUALSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.bbva.originacion.ws.oi.WSOriginacionIndividualService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.bbva.originacion.ws.oi.WSOriginacionIndividualService.class.getResource(".");
			url = new URL(baseUrl, ParametrosOriginacion.wsOriginacion[ParametrosOriginacion.entorno]);
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://150.50.102.88:16031/gestion/services/WSOriginacionIndividual?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WSORIGINACIONINDIVIDUALSERVICE_WSDL_LOCATION = url;
	}

	public WSOriginacionIndividualService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WSOriginacionIndividualService() {
		super(WSORIGINACIONINDIVIDUALSERVICE_WSDL_LOCATION,
				new QName("http://oi.ws.bancomer.com", "WSOriginacionIndividualService"));
	}

	/**
	 * 
	 * @return returns WSOriginacionIndividualSEI
	 */
	@WebEndpoint(name = "WSOriginacionIndividual")
	public WSOriginacionIndividualSEI getWSOriginacionIndividual() {
		return super.getPort(new QName("http://oi.ws.bancomer.com", "WSOriginacionIndividual"),
				WSOriginacionIndividualSEI.class);
	}

}
