
package com.bbva.originacion.ws.oi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSOriginacionIndividual_SEI", targetNamespace = "http://oi.ws.bancomer.com")
public interface WSOriginacionIndividualSEI {

	/**
	 * 
	 * @param listaCampos
	 * @param gaveta
	 * @param listaValores
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "creaExpedienteIdxReturn", targetNamespace = "")
	@RequestWrapper(localName = "creaExpedienteIdx", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.CreaExpedienteIdx")
	@ResponseWrapper(localName = "creaExpedienteIdxResponse", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.CreaExpedienteIdxResponse")
	public String creaExpedienteIdx(@WebParam(name = "gaveta", targetNamespace = "") String gaveta,
			@WebParam(name = "lista_campos", targetNamespace = "") String listaCampos,
			@WebParam(name = "lista_valores", targetNamespace = "") String listaValores);

	/**
	 * 
	 * @param listaCampos
	 * @param archivo
	 * @param gaveta
	 * @param listaValores
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "recibeArchivosIdxReturn", targetNamespace = "")
	@RequestWrapper(localName = "recibeArchivosIdx", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.RecibeArchivosIdx")
	@ResponseWrapper(localName = "recibeArchivosIdxResponse", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.RecibeArchivosIdxResponse")
	public String recibeArchivosIdx(@WebParam(name = "gaveta", targetNamespace = "") String gaveta,
			@WebParam(name = "lista_campos", targetNamespace = "") String listaCampos,
			@WebParam(name = "lista_valores", targetNamespace = "") String listaValores,
			@WebParam(name = "archivo", targetNamespace = "") byte[] archivo);

	/**
	 * 
	 * @param listaCampos
	 * @param gaveta
	 * @param listaValores
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "totalPaginasDoctoIdxReturn", targetNamespace = "")
	@RequestWrapper(localName = "totalPaginasDoctoIdx", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.TotalPaginasDoctoIdx")
	@ResponseWrapper(localName = "totalPaginasDoctoIdxResponse", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.TotalPaginasDoctoIdxResponse")
	public String totalPaginasDoctoIdx(@WebParam(name = "gaveta", targetNamespace = "") String gaveta,
			@WebParam(name = "lista_campos", targetNamespace = "") String listaCampos,
			@WebParam(name = "lista_valores", targetNamespace = "") String listaValores);

	/**
	 * 
	 * @param listaCampos
	 * @param gaveta
	 * @param listaValores
	 * @return returns byte[]
	 */
	@WebMethod
	@WebResult(name = "envioImagenesIdxReturn", targetNamespace = "")
	@RequestWrapper(localName = "envioImagenesIdx", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.EnvioImagenesIdx")
	@ResponseWrapper(localName = "envioImagenesIdxResponse", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.EnvioImagenesIdxResponse")
	public byte[] envioImagenesIdx(@WebParam(name = "gaveta", targetNamespace = "") String gaveta,
			@WebParam(name = "lista_campos", targetNamespace = "") String listaCampos,
			@WebParam(name = "lista_valores", targetNamespace = "") String listaValores);

	/**
	 * 
	 * @param listaCampos
	 * @param gaveta
	 * @param listaValores
	 * @return returns com.bancomer.ws.oi.ArrayOfArrayOfXsdNillableString
	 */
	@WebMethod
	@WebResult(name = "listaDocumentosIdxReturn", targetNamespace = "")
	@RequestWrapper(localName = "listaDocumentosIdx", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.ListaDocumentosIdx")
	@ResponseWrapper(localName = "listaDocumentosIdxResponse", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.ListaDocumentosIdxResponse")
	public ArrayOfArrayOfXsdNillableString listaDocumentosIdx(
			@WebParam(name = "gaveta", targetNamespace = "") String gaveta,
			@WebParam(name = "lista_campos", targetNamespace = "") String listaCampos,
			@WebParam(name = "lista_valores", targetNamespace = "") String listaValores);

	/**
	 * 
	 * @param listaCampos
	 * @param gaveta
	 * @param listaValores
	 * @return returns com.bancomer.ws.oi.WSDocumento
	 */
	@WebMethod
	@WebResult(name = "getDocumentoReturn", targetNamespace = "")
	@RequestWrapper(localName = "getDocumento", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.GetDocumento")
	@ResponseWrapper(localName = "getDocumentoResponse", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.GetDocumentoResponse")
	public WSDocumento getDocumento(@WebParam(name = "gaveta", targetNamespace = "") String gaveta,
			@WebParam(name = "lista_campos", targetNamespace = "") String listaCampos,
			@WebParam(name = "lista_valores", targetNamespace = "") String listaValores);

	/**
	 * 
	 * @param listaCampos
	 * @param gaveta
	 * @param listaValores
	 * @return returns byte[]
	 */
	@WebMethod
	@WebResult(name = "getFormatFileReturn", targetNamespace = "")
	@RequestWrapper(localName = "getFormatFile", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.GetFormatFile")
	@ResponseWrapper(localName = "getFormatFileResponse", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.GetFormatFileResponse")
	public byte[] getFormatFile(@WebParam(name = "gaveta", targetNamespace = "") String gaveta,
			@WebParam(name = "lista_campos", targetNamespace = "") String listaCampos,
			@WebParam(name = "lista_valores", targetNamespace = "") String listaValores);

	/**
	 * 
	 * @param listaCampos
	 * @param archivo
	 * @param gaveta
	 * @param listaValores
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "recibeArchivosReturn", targetNamespace = "")
	@RequestWrapper(localName = "recibeArchivos", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.RecibeArchivos")
	@ResponseWrapper(localName = "recibeArchivosResponse", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.RecibeArchivosResponse")
	public String recibeArchivos(@WebParam(name = "gaveta", targetNamespace = "") String gaveta,
			@WebParam(name = "lista_campos", targetNamespace = "") String listaCampos,
			@WebParam(name = "lista_valores", targetNamespace = "") String listaValores,
			@WebParam(name = "archivo", targetNamespace = "") byte[] archivo);

	/**
	 * 
	 * @param listaCampos
	 * @param gaveta
	 * @param listaValores
	 * @return returns com.bancomer.ws.oi.ArrayOfXsdBase64Binary
	 */
	@WebMethod
	@WebResult(name = "envioImagenesDocumentoReturn", targetNamespace = "")
	@RequestWrapper(localName = "envioImagenesDocumento", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.EnvioImagenesDocumento")
	@ResponseWrapper(localName = "envioImagenesDocumentoResponse", targetNamespace = "http://oi.ws.bancomer.com", className = "com.bancomer.ws.oi.EnvioImagenesDocumentoResponse")
	public ArrayOfXsdBase64Binary envioImagenesDocumento(@WebParam(name = "gaveta", targetNamespace = "") String gaveta,
			@WebParam(name = "lista_campos", targetNamespace = "") String listaCampos,
			@WebParam(name = "lista_valores", targetNamespace = "") String listaValores);

}
