package mx.bbva.bancomer.hsm.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import mx.bbva.bancomer.hsm.bean.ResponseBean;
import mx.bbva.bancomer.hsm.bean.UserBean;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSSeguridadHSM", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx")
public interface WSSeguridadHSM {

	/**
	 * 
	 * @param usuario
	 * @param nombreLlave
	 * @param flujoEntrada
	 * @return returns mx.bbva.bancomer.hsm.bean.ResponseBean
	 */
	@WebMethod
	@WebResult(name = "cifrarArchivoXMLReturn", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx")
	@RequestWrapper(localName = "cifrarArchivoXML", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx", className = "mx.bbva.bancomer.hsm.wsdl.CifrarArchivoXML")
	@ResponseWrapper(localName = "cifrarArchivoXMLResponse", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx", className = "mx.bbva.bancomer.hsm.wsdl.CifrarArchivoXMLResponse")
	public ResponseBean cifrarArchivoXML(
			@WebParam(name = "nombreLlave", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx") String nombreLlave,
			@WebParam(name = "flujoEntrada", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx") byte[] flujoEntrada,
			@WebParam(name = "usuario", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx") UserBean usuario);

	/**
	 * 
	 * @param usuario
	 * @param nombreLlave
	 * @param flujoEntrada
	 * @return returns mx.bbva.bancomer.hsm.bean.ResponseBean
	 */
	@WebMethod
	@WebResult(name = "descifrarArchivoXMLReturn", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx")
	@RequestWrapper(localName = "descifrarArchivoXML", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx", className = "mx.bbva.bancomer.hsm.wsdl.DescifrarArchivoXML")
	@ResponseWrapper(localName = "descifrarArchivoXMLResponse", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx", className = "mx.bbva.bancomer.hsm.wsdl.DescifrarArchivoXMLResponse")
	public ResponseBean descifrarArchivoXML(
			@WebParam(name = "nombreLlave", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx") String nombreLlave,
			@WebParam(name = "flujoEntrada", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx") byte[] flujoEntrada,
			@WebParam(name = "usuario", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx") UserBean usuario);

}
