package mx.bbva.bancomer.hsm.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WSSeguridadHSMService service = new WSSeguridadHSMService();
 * WSSeguridadHSM portType = service.getWSSeguridadHSM();
 * portType.cifrarArchivoXML(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WSSeguridadHSMService", targetNamespace = "http://wsdl.hsm.bancomer.bbva.mx", wsdlLocation = "https://150.250.235.63/BBVAMexico/services/WSSeguridadHSM?wsdl")
public class WSSeguridadHSMService extends Service {

	private final static URL WSSEGURIDADHSMSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(mx.bbva.bancomer.hsm.wsdl.WSSeguridadHSMService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = mx.bbva.bancomer.hsm.wsdl.WSSeguridadHSMService.class
					.getResource(".");
			url = new URL(baseUrl,
					"https://150.250.235.63/BBVAMexico/services/WSSeguridadHSM?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'https://150.250.235.63/BBVAMexico/services/WSSeguridadHSM?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WSSEGURIDADHSMSERVICE_WSDL_LOCATION = url;
	}

	public WSSeguridadHSMService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WSSeguridadHSMService() {
		super(WSSEGURIDADHSMSERVICE_WSDL_LOCATION, new QName(
				"http://wsdl.hsm.bancomer.bbva.mx", "WSSeguridadHSMService"));
	}

	/**
	 * 
	 * @return returns WSSeguridadHSM
	 */
	@WebEndpoint(name = "WSSeguridadHSM")
	public WSSeguridadHSM getWSSeguridadHSM() {
		return super.getPort(new QName("http://wsdl.hsm.bancomer.bbva.mx",
				"WSSeguridadHSM"), WSSeguridadHSM.class);
	}

}
