//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.syc.bbva.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for getDocumento complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="getDocumento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="folioDig" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cveDocto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDocumento", namespace = "http://ws.bbva.syc.com/", propOrder = {
		"folioDig", "cveDocto" })
public class GetDocumento {

	protected String folioDig;
	protected String cveDocto;

	/**
	 * Gets the value of the folioDig property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFolioDig() {
		return folioDig;
	}

	/**
	 * Sets the value of the folioDig property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFolioDig(String value) {
		this.folioDig = value;
	}

	/**
	 * Gets the value of the cveDocto property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCveDocto() {
		return cveDocto;
	}

	/**
	 * Sets the value of the cveDocto property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCveDocto(String value) {
		this.cveDocto = value;
	}

}
