//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.syc.bbva.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for getDocumentoResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="getDocumentoResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="return" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getDocumentoResponse", namespace = "http://ws.bbva.syc.com/", propOrder = { "_return" })
public class GetDocumentoResponse {

	@XmlElementRef(name = "return", type = JAXBElement.class)
	protected JAXBElement<byte[]> _return;

	/**
	 * Gets the value of the return property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link byte[]}
	 *         {@code >}
	 * 
	 */
	public JAXBElement<byte[]> getReturn() {
		return _return;
	}

	/**
	 * Sets the value of the return property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link byte[]}
	 *            {@code >}
	 * 
	 */
	public void setReturn(JAXBElement<byte[]> value) {
		this._return = ((JAXBElement<byte[]>) value);
	}

}
