//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.syc.bbva.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for getGenericFile complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="getGenericFile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xslFoB64" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="extension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="auxiliar" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getGenericFile", namespace = "http://ws.bbva.syc.com/", propOrder = {
		"xslFoB64", "extension", "auxiliar" })
public class GetGenericFile {

	@XmlElementRef(name = "xslFoB64", type = JAXBElement.class)
	protected JAXBElement<byte[]> xslFoB64;
	protected String extension;
	protected String auxiliar;

	/**
	 * Gets the value of the xslFoB64 property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link byte[]}
	 *         {@code >}
	 * 
	 */
	public JAXBElement<byte[]> getXslFoB64() {
		return xslFoB64;
	}

	/**
	 * Sets the value of the xslFoB64 property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link byte[]}
	 *            {@code >}
	 * 
	 */
	public void setXslFoB64(JAXBElement<byte[]> value) {
		this.xslFoB64 = ((JAXBElement<byte[]>) value);
	}

	/**
	 * Gets the value of the extension property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExtension() {
		return extension;
	}

	/**
	 * Sets the value of the extension property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExtension(String value) {
		this.extension = value;
	}

	/**
	 * Gets the value of the auxiliar property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAuxiliar() {
		return auxiliar;
	}

	/**
	 * Sets the value of the auxiliar property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAuxiliar(String value) {
		this.auxiliar = value;
	}

}
