//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.syc.bbva.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.syc.bbva.ws package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _RecibeFOResponse_QNAME = new QName(
			"http://ws.bbva.syc.com/", "recibeFOResponse");
	private final static QName _SaveInfoBuroScoring_QNAME = new QName(
			"http://ws.bbva.syc.com/", "saveInfoBuroScoring");
	private final static QName _GetGenericFile_QNAME = new QName(
			"http://ws.bbva.syc.com/", "getGenericFile");
	private final static QName _RecibeInformacion_QNAME = new QName(
			"http://ws.bbva.syc.com/", "recibeInformacion");
	private final static QName _RecibePDF_QNAME = new QName(
			"http://ws.bbva.syc.com/", "recibePDF");
	private final static QName _RecibeXML_QNAME = new QName(
			"http://ws.bbva.syc.com/", "recibeXML");
	private final static QName _SendDocumentsByMailResponse_QNAME = new QName(
			"http://ws.bbva.syc.com/", "sendDocumentsByMailResponse");
	private final static QName _RecibeFO_QNAME = new QName(
			"http://ws.bbva.syc.com/", "recibeFO");
	private final static QName _GetGenericFileResponse_QNAME = new QName(
			"http://ws.bbva.syc.com/", "getGenericFileResponse");
	private final static QName _SendDocumentsByMail_QNAME = new QName(
			"http://ws.bbva.syc.com/", "sendDocumentsByMail");
	private final static QName _RecibeInformacionResponse_QNAME = new QName(
			"http://ws.bbva.syc.com/", "recibeInformacionResponse");
	private final static QName _SendInfoMailResponse_QNAME = new QName(
			"http://ws.bbva.syc.com/", "sendInfoMailResponse");
	private final static QName _GetDocumentoResponse_QNAME = new QName(
			"http://ws.bbva.syc.com/", "getDocumentoResponse");
	private final static QName _ValidaMSDResponse_QNAME = new QName(
			"http://ws.bbva.syc.com/", "validaMSDResponse");
	private final static QName _ResendInfoMail_QNAME = new QName(
			"http://ws.bbva.syc.com/", "resendInfoMail");
	private final static QName _ResendInfoMailResponse_QNAME = new QName(
			"http://ws.bbva.syc.com/", "resendInfoMailResponse");
	private final static QName _RecibePDFResponse_QNAME = new QName(
			"http://ws.bbva.syc.com/", "recibePDFResponse");
	private final static QName _SaveInfoBuroScoringResponse_QNAME = new QName(
			"http://ws.bbva.syc.com/", "saveInfoBuroScoringResponse");
	private final static QName _GetDocumento_QNAME = new QName(
			"http://ws.bbva.syc.com/", "getDocumento");
	private final static QName _RecibeXMLResponse_QNAME = new QName(
			"http://ws.bbva.syc.com/", "recibeXMLResponse");
	private final static QName _SendInfoMail_QNAME = new QName(
			"http://ws.bbva.syc.com/", "sendInfoMail");
	private final static QName _ValidaMSD_QNAME = new QName(
			"http://ws.bbva.syc.com/", "validaMSD");
	private final static QName _RecibeXMLArg0_QNAME = new QName("", "arg0");
	private final static QName _GetDocumentoResponseReturn_QNAME = new QName(
			"", "return");
	private final static QName _RecibeFOGenericFile_QNAME = new QName("",
			"genericFile");
	private final static QName _GetGenericFileXslFoB64_QNAME = new QName("",
			"xslFoB64");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.syc.bbva.ws
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link SendInfoMailResponse }
	 * 
	 */
	public SendInfoMailResponse createSendInfoMailResponse() {
		return new SendInfoMailResponse();
	}

	/**
	 * Create an instance of {@link SaveInfoBuroScoring }
	 * 
	 */
	public SaveInfoBuroScoring createSaveInfoBuroScoring() {
		return new SaveInfoBuroScoring();
	}

	/**
	 * Create an instance of {@link RecibeFOResponse }
	 * 
	 */
	public RecibeFOResponse createRecibeFOResponse() {
		return new RecibeFOResponse();
	}

	/**
	 * Create an instance of {@link ResendInfoMailResponse }
	 * 
	 */
	public ResendInfoMailResponse createResendInfoMailResponse() {
		return new ResendInfoMailResponse();
	}

	/**
	 * Create an instance of {@link RecibeXML }
	 * 
	 */
	public RecibeXML createRecibeXML() {
		return new RecibeXML();
	}

	/**
	 * Create an instance of {@link ValidaMSDResponse }
	 * 
	 */
	public ValidaMSDResponse createValidaMSDResponse() {
		return new ValidaMSDResponse();
	}

	/**
	 * Create an instance of {@link ValidaMSD }
	 * 
	 */
	public ValidaMSD createValidaMSD() {
		return new ValidaMSD();
	}

	/**
	 * Create an instance of {@link GetDocumentoResponse }
	 * 
	 */
	public GetDocumentoResponse createGetDocumentoResponse() {
		return new GetDocumentoResponse();
	}

	/**
	 * Create an instance of {@link GetGenericFileResponse }
	 * 
	 */
	public GetGenericFileResponse createGetGenericFileResponse() {
		return new GetGenericFileResponse();
	}

	/**
	 * Create an instance of {@link RecibeFO }
	 * 
	 */
	public RecibeFO createRecibeFO() {
		return new RecibeFO();
	}

	/**
	 * Create an instance of {@link RecibePDFResponse }
	 * 
	 */
	public RecibePDFResponse createRecibePDFResponse() {
		return new RecibePDFResponse();
	}

	/**
	 * Create an instance of {@link RecibeInformacionResponse }
	 * 
	 */
	public RecibeInformacionResponse createRecibeInformacionResponse() {
		return new RecibeInformacionResponse();
	}

	/**
	 * Create an instance of {@link SendInfoMail }
	 * 
	 */
	public SendInfoMail createSendInfoMail() {
		return new SendInfoMail();
	}

	/**
	 * Create an instance of {@link SendDocumentsByMailResponse }
	 * 
	 */
	public SendDocumentsByMailResponse createSendDocumentsByMailResponse() {
		return new SendDocumentsByMailResponse();
	}

	/**
	 * Create an instance of {@link SendDocumentsByMail }
	 * 
	 */
	public SendDocumentsByMail createSendDocumentsByMail() {
		return new SendDocumentsByMail();
	}

	/**
	 * Create an instance of {@link GetDocumento }
	 * 
	 */
	public GetDocumento createGetDocumento() {
		return new GetDocumento();
	}

	/**
	 * Create an instance of {@link RecibeXMLResponse }
	 * 
	 */
	public RecibeXMLResponse createRecibeXMLResponse() {
		return new RecibeXMLResponse();
	}

	/**
	 * Create an instance of {@link SaveInfoBuroScoringResponse }
	 * 
	 */
	public SaveInfoBuroScoringResponse createSaveInfoBuroScoringResponse() {
		return new SaveInfoBuroScoringResponse();
	}

	/**
	 * Create an instance of {@link RecibePDF }
	 * 
	 */
	public RecibePDF createRecibePDF() {
		return new RecibePDF();
	}

	/**
	 * Create an instance of {@link GetGenericFile }
	 * 
	 */
	public GetGenericFile createGetGenericFile() {
		return new GetGenericFile();
	}

	/**
	 * Create an instance of {@link ResendInfoMail }
	 * 
	 */
	public ResendInfoMail createResendInfoMail() {
		return new ResendInfoMail();
	}

	/**
	 * Create an instance of {@link RecibeInformacion }
	 * 
	 */
	public RecibeInformacion createRecibeInformacion() {
		return new RecibeInformacion();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link RecibeFOResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "recibeFOResponse")
	public JAXBElement<RecibeFOResponse> createRecibeFOResponse(
			RecibeFOResponse value) {
		return new JAXBElement<RecibeFOResponse>(_RecibeFOResponse_QNAME,
				RecibeFOResponse.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link SaveInfoBuroScoring }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "saveInfoBuroScoring")
	public JAXBElement<SaveInfoBuroScoring> createSaveInfoBuroScoring(
			SaveInfoBuroScoring value) {
		return new JAXBElement<SaveInfoBuroScoring>(_SaveInfoBuroScoring_QNAME,
				SaveInfoBuroScoring.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link GetGenericFile }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "getGenericFile")
	public JAXBElement<GetGenericFile> createGetGenericFile(GetGenericFile value) {
		return new JAXBElement<GetGenericFile>(_GetGenericFile_QNAME,
				GetGenericFile.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link RecibeInformacion }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "recibeInformacion")
	public JAXBElement<RecibeInformacion> createRecibeInformacion(
			RecibeInformacion value) {
		return new JAXBElement<RecibeInformacion>(_RecibeInformacion_QNAME,
				RecibeInformacion.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link RecibePDF }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "recibePDF")
	public JAXBElement<RecibePDF> createRecibePDF(RecibePDF value) {
		return new JAXBElement<RecibePDF>(_RecibePDF_QNAME, RecibePDF.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link RecibeXML }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "recibeXML")
	public JAXBElement<RecibeXML> createRecibeXML(RecibeXML value) {
		return new JAXBElement<RecibeXML>(_RecibeXML_QNAME, RecibeXML.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link SendDocumentsByMailResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "sendDocumentsByMailResponse")
	public JAXBElement<SendDocumentsByMailResponse> createSendDocumentsByMailResponse(
			SendDocumentsByMailResponse value) {
		return new JAXBElement<SendDocumentsByMailResponse>(
				_SendDocumentsByMailResponse_QNAME,
				SendDocumentsByMailResponse.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link RecibeFO }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "recibeFO")
	public JAXBElement<RecibeFO> createRecibeFO(RecibeFO value) {
		return new JAXBElement<RecibeFO>(_RecibeFO_QNAME, RecibeFO.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link GetGenericFileResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "getGenericFileResponse")
	public JAXBElement<GetGenericFileResponse> createGetGenericFileResponse(
			GetGenericFileResponse value) {
		return new JAXBElement<GetGenericFileResponse>(
				_GetGenericFileResponse_QNAME, GetGenericFileResponse.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link SendDocumentsByMail }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "sendDocumentsByMail")
	public JAXBElement<SendDocumentsByMail> createSendDocumentsByMail(
			SendDocumentsByMail value) {
		return new JAXBElement<SendDocumentsByMail>(_SendDocumentsByMail_QNAME,
				SendDocumentsByMail.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link RecibeInformacionResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "recibeInformacionResponse")
	public JAXBElement<RecibeInformacionResponse> createRecibeInformacionResponse(
			RecibeInformacionResponse value) {
		return new JAXBElement<RecibeInformacionResponse>(
				_RecibeInformacionResponse_QNAME,
				RecibeInformacionResponse.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link SendInfoMailResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "sendInfoMailResponse")
	public JAXBElement<SendInfoMailResponse> createSendInfoMailResponse(
			SendInfoMailResponse value) {
		return new JAXBElement<SendInfoMailResponse>(
				_SendInfoMailResponse_QNAME, SendInfoMailResponse.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link GetDocumentoResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "getDocumentoResponse")
	public JAXBElement<GetDocumentoResponse> createGetDocumentoResponse(
			GetDocumentoResponse value) {
		return new JAXBElement<GetDocumentoResponse>(
				_GetDocumentoResponse_QNAME, GetDocumentoResponse.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link ValidaMSDResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "validaMSDResponse")
	public JAXBElement<ValidaMSDResponse> createValidaMSDResponse(
			ValidaMSDResponse value) {
		return new JAXBElement<ValidaMSDResponse>(_ValidaMSDResponse_QNAME,
				ValidaMSDResponse.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ResendInfoMail }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "resendInfoMail")
	public JAXBElement<ResendInfoMail> createResendInfoMail(ResendInfoMail value) {
		return new JAXBElement<ResendInfoMail>(_ResendInfoMail_QNAME,
				ResendInfoMail.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link ResendInfoMailResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "resendInfoMailResponse")
	public JAXBElement<ResendInfoMailResponse> createResendInfoMailResponse(
			ResendInfoMailResponse value) {
		return new JAXBElement<ResendInfoMailResponse>(
				_ResendInfoMailResponse_QNAME, ResendInfoMailResponse.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link RecibePDFResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "recibePDFResponse")
	public JAXBElement<RecibePDFResponse> createRecibePDFResponse(
			RecibePDFResponse value) {
		return new JAXBElement<RecibePDFResponse>(_RecibePDFResponse_QNAME,
				RecibePDFResponse.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link SaveInfoBuroScoringResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "saveInfoBuroScoringResponse")
	public JAXBElement<SaveInfoBuroScoringResponse> createSaveInfoBuroScoringResponse(
			SaveInfoBuroScoringResponse value) {
		return new JAXBElement<SaveInfoBuroScoringResponse>(
				_SaveInfoBuroScoringResponse_QNAME,
				SaveInfoBuroScoringResponse.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link GetDocumento }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "getDocumento")
	public JAXBElement<GetDocumento> createGetDocumento(GetDocumento value) {
		return new JAXBElement<GetDocumento>(_GetDocumento_QNAME,
				GetDocumento.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link RecibeXMLResponse }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "recibeXMLResponse")
	public JAXBElement<RecibeXMLResponse> createRecibeXMLResponse(
			RecibeXMLResponse value) {
		return new JAXBElement<RecibeXMLResponse>(_RecibeXMLResponse_QNAME,
				RecibeXMLResponse.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link SendInfoMail }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "sendInfoMail")
	public JAXBElement<SendInfoMail> createSendInfoMail(SendInfoMail value) {
		return new JAXBElement<SendInfoMail>(_SendInfoMail_QNAME,
				SendInfoMail.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ValidaMSD }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ws.bbva.syc.com/", name = "validaMSD")
	public JAXBElement<ValidaMSD> createValidaMSD(ValidaMSD value) {
		return new JAXBElement<ValidaMSD>(_ValidaMSD_QNAME, ValidaMSD.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "arg0", scope = RecibeXML.class)
	public JAXBElement<byte[]> createRecibeXMLArg0(byte[] value) {
		return new JAXBElement<byte[]>(_RecibeXMLArg0_QNAME, byte[].class,
				RecibeXML.class, ((byte[]) value));
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "arg0", scope = RecibePDF.class)
	public JAXBElement<byte[]> createRecibePDFArg0(byte[] value) {
		return new JAXBElement<byte[]>(_RecibeXMLArg0_QNAME, byte[].class,
				RecibePDF.class, ((byte[]) value));
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "return", scope = GetDocumentoResponse.class)
	public JAXBElement<byte[]> createGetDocumentoResponseReturn(byte[] value) {
		return new JAXBElement<byte[]>(_GetDocumentoResponseReturn_QNAME,
				byte[].class, GetDocumentoResponse.class, ((byte[]) value));
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "genericFile", scope = RecibeFO.class)
	public JAXBElement<byte[]> createRecibeFOGenericFile(byte[] value) {
		return new JAXBElement<byte[]>(_RecibeFOGenericFile_QNAME,
				byte[].class, RecibeFO.class, ((byte[]) value));
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "xslFoB64", scope = GetGenericFile.class)
	public JAXBElement<byte[]> createGetGenericFileXslFoB64(byte[] value) {
		return new JAXBElement<byte[]>(_GetGenericFileXslFoB64_QNAME,
				byte[].class, GetGenericFile.class, ((byte[]) value));
	}

}
