//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.syc.bbva.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

@WebServiceClient(name = "RecibeContratoService", targetNamespace = "http://ws.bbva.syc.com/", wsdlLocation = "http://150.100.43.176:7051/LLFirmaDigital/RecibeContratoService/WEB-INF/wsdl/RecibeContratoService.wsdl")
public class RecibeContratoService extends Service {

	private final static URL RECIBECONTRATOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.syc.bbva.ws.RecibeContratoService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.syc.bbva.ws.RecibeContratoService.class
					.getResource(".");
			url = new URL(
					baseUrl,
//					"http://150.250.235.63:1446/LLFirmaDigital/RecibeContratoService/WEB-INF/wsdl/RecibeContratoService.wsdl");
					"http://150.250.234.123:36081/LLFirmaDigital/RecibeContratoService/WEB-INF/wsdl/RecibeContratoService.wsdl");
//					"http://150.100.43.176:7051/LLFirmaDigital/RecibeContratoService/WEB-INF/wsdl/RecibeContratoService.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://150.100.43.176:7051/LLFirmaDigital/RecibeContratoService/WEB-INF/wsdl/RecibeContratoService.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		RECIBECONTRATOSERVICE_WSDL_LOCATION = url;
	}

	public RecibeContratoService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public RecibeContratoService() {
		super(RECIBECONTRATOSERVICE_WSDL_LOCATION, new QName(
				"http://ws.bbva.syc.com/", "RecibeContratoService"));
	}

	/**
	 * 
	 * @return returns RecibeContratoDelegate
	 */
	@WebEndpoint(name = "RecibeContratoPort")
	public RecibeContratoDelegate getRecibeContratoPort() {
		return super.getPort(new QName("http://ws.bbva.syc.com/",
				"RecibeContratoPort"), RecibeContratoDelegate.class);
	}
}
