//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.syc.bbva.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for resendInfoMail complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="resendInfoMail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroCliente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="folioDig" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroContrato" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="claveDocumento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="correoE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contrasenia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resendInfoMail", namespace = "http://ws.bbva.syc.com/", propOrder = {
		"numeroCliente", "folioDig", "numeroContrato", "claveDocumento",
		"correoE", "contrasenia" })
public class ResendInfoMail {

	protected String numeroCliente;
	protected String folioDig;
	protected String numeroContrato;
	protected String claveDocumento;
	protected String correoE;
	protected String contrasenia;

	/**
	 * Gets the value of the numeroCliente property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumeroCliente() {
		return numeroCliente;
	}

	/**
	 * Sets the value of the numeroCliente property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumeroCliente(String value) {
		this.numeroCliente = value;
	}

	/**
	 * Gets the value of the folioDig property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFolioDig() {
		return folioDig;
	}

	/**
	 * Sets the value of the folioDig property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFolioDig(String value) {
		this.folioDig = value;
	}

	/**
	 * Gets the value of the numeroContrato property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumeroContrato() {
		return numeroContrato;
	}

	/**
	 * Sets the value of the numeroContrato property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumeroContrato(String value) {
		this.numeroContrato = value;
	}

	/**
	 * Gets the value of the claveDocumento property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClaveDocumento() {
		return claveDocumento;
	}

	/**
	 * Sets the value of the claveDocumento property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClaveDocumento(String value) {
		this.claveDocumento = value;
	}

	/**
	 * Gets the value of the correoE property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCorreoE() {
		return correoE;
	}

	/**
	 * Sets the value of the correoE property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCorreoE(String value) {
		this.correoE = value;
	}

	/**
	 * Gets the value of the contrasenia property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContrasenia() {
		return contrasenia;
	}

	/**
	 * Sets the value of the contrasenia property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContrasenia(String value) {
		this.contrasenia = value;
	}

}
