//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.syc.bbva.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for saveInfoBuroScoring complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="saveInfoBuroScoring">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numCliente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numContrato" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusPropuesta" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cvesDoctos" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idTerminal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idUsuario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saveInfoBuroScoring", namespace = "http://ws.bbva.syc.com/", propOrder = {
		"numCliente", "numContrato", "statusPropuesta", "cvesDoctos", "cr",
		"idTerminal", "idUsuario" })
public class SaveInfoBuroScoring {

	protected String numCliente;
	protected String numContrato;
	protected String statusPropuesta;
	protected List<String> cvesDoctos;
	protected String cr;
	protected String idTerminal;
	protected String idUsuario;

	/**
	 * Gets the value of the numCliente property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumCliente() {
		return numCliente;
	}

	/**
	 * Sets the value of the numCliente property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumCliente(String value) {
		this.numCliente = value;
	}

	/**
	 * Gets the value of the numContrato property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumContrato() {
		return numContrato;
	}

	/**
	 * Sets the value of the numContrato property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumContrato(String value) {
		this.numContrato = value;
	}

	/**
	 * Gets the value of the statusPropuesta property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatusPropuesta() {
		return statusPropuesta;
	}

	/**
	 * Sets the value of the statusPropuesta property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatusPropuesta(String value) {
		this.statusPropuesta = value;
	}

	/**
	 * Gets the value of the cvesDoctos property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the cvesDoctos property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCvesDoctos().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getCvesDoctos() {
		if (cvesDoctos == null) {
			cvesDoctos = new ArrayList<String>();
		}
		return this.cvesDoctos;
	}

	/**
	 * Gets the value of the cr property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCr() {
		return cr;
	}

	/**
	 * Sets the value of the cr property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCr(String value) {
		this.cr = value;
	}

	/**
	 * Gets the value of the idTerminal property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdTerminal() {
		return idTerminal;
	}

	/**
	 * Sets the value of the idTerminal property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdTerminal(String value) {
		this.idTerminal = value;
	}

	/**
	 * Gets the value of the idUsuario property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdUsuario() {
		return idUsuario;
	}

	/**
	 * Sets the value of the idUsuario property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdUsuario(String value) {
		this.idUsuario = value;
	}

}
