//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.syc.bbva.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for sendDocumentsByMail complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="sendDocumentsByMail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroCliente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroContrato" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="marca" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="infoProd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="infoEnvio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="foliosDig" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="comentarios" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="crSuc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="telSuc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nomEjecutivo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="correoE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendDocumentsByMail", namespace = "http://ws.bbva.syc.com/", propOrder = {
		"numeroCliente", "numeroContrato", "marca", "infoProd", "infoEnvio",
		"foliosDig", "comentarios", "crSuc", "telSuc", "nomEjecutivo",
		"correoE" })
public class SendDocumentsByMail {

	protected String numeroCliente;
	protected String numeroContrato;
	protected String marca;
	protected String infoProd;
	protected String infoEnvio;
	@XmlElement(nillable = true)
	protected List<String> foliosDig;
	protected String comentarios;
	protected String crSuc;
	protected String telSuc;
	protected String nomEjecutivo;
	protected String correoE;

	/**
	 * Gets the value of the numeroCliente property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumeroCliente() {
		return numeroCliente;
	}

	/**
	 * Sets the value of the numeroCliente property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumeroCliente(String value) {
		this.numeroCliente = value;
	}

	/**
	 * Gets the value of the numeroContrato property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumeroContrato() {
		return numeroContrato;
	}

	/**
	 * Sets the value of the numeroContrato property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumeroContrato(String value) {
		this.numeroContrato = value;
	}

	/**
	 * Gets the value of the marca property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMarca() {
		return marca;
	}

	/**
	 * Sets the value of the marca property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMarca(String value) {
		this.marca = value;
	}

	/**
	 * Gets the value of the infoProd property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInfoProd() {
		return infoProd;
	}

	/**
	 * Sets the value of the infoProd property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInfoProd(String value) {
		this.infoProd = value;
	}

	/**
	 * Gets the value of the infoEnvio property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInfoEnvio() {
		return infoEnvio;
	}

	/**
	 * Sets the value of the infoEnvio property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInfoEnvio(String value) {
		this.infoEnvio = value;
	}

	/**
	 * Gets the value of the foliosDig property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the foliosDig property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFoliosDig().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getFoliosDig() {
		if (foliosDig == null) {
			foliosDig = new ArrayList<String>();
		}
		return this.foliosDig;
	}

	/**
	 * Gets the value of the comentarios property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getComentarios() {
		return comentarios;
	}

	/**
	 * Sets the value of the comentarios property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setComentarios(String value) {
		this.comentarios = value;
	}

	/**
	 * Gets the value of the crSuc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCrSuc() {
		return crSuc;
	}

	/**
	 * Sets the value of the crSuc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCrSuc(String value) {
		this.crSuc = value;
	}

	/**
	 * Gets the value of the telSuc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTelSuc() {
		return telSuc;
	}

	/**
	 * Sets the value of the telSuc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTelSuc(String value) {
		this.telSuc = value;
	}

	/**
	 * Gets the value of the nomEjecutivo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNomEjecutivo() {
		return nomEjecutivo;
	}

	/**
	 * Sets the value of the nomEjecutivo property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNomEjecutivo(String value) {
		this.nomEjecutivo = value;
	}

	/**
	 * Gets the value of the correoE property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCorreoE() {
		return correoE;
	}

	/**
	 * Sets the value of the correoE property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCorreoE(String value) {
		this.correoE = value;
	}

}
