
package com.bbva.live.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* WSLiveServicePortImpService service = new WSLiveServicePortImpService();
* WSLiveServicePortImpDelegate portType = service.getWSLiveServicePortImpPort();
* portType.enviaExpediente(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "WSLiveServicePortImpService", targetNamespace = "http://ws.live.bbva.com/", wsdlLocation = "http://150.100.210.236:36015/fimxlive/WSLiveServicePortImpPort?wsdl")
public class WSLiveServicePortImpService extends Service {

	private final static URL WSLIVESERVICEPORTIMPSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.bbva.live.ws.WSLiveServicePortImpService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.bbva.live.ws.WSLiveServicePortImpService.class.getResource(".");
			url = new URL(baseUrl, "http://150.100.43.220:36015/fimxlive/WSLiveServicePortImpPort?wsdl"); //PRODU
//			url = new URL(baseUrl, "http://localhost:9081/fimxlive/WSLiveServicePortImpPort?wsdl"); //RAFITA
			
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://150.100.210.236:36015/fimxlive/WSLiveServicePortImpPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WSLIVESERVICEPORTIMPSERVICE_WSDL_LOCATION = url;
	}

	public WSLiveServicePortImpService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WSLiveServicePortImpService() {
		super(WSLIVESERVICEPORTIMPSERVICE_WSDL_LOCATION,
				new QName("http://ws.live.bbva.com/", "WSLiveServicePortImpService"));
	}

	/**
	 * 
	 * @return returns WSLiveServicePortImpDelegate
	 */
	@WebEndpoint(name = "WSLiveServicePortImpPort")
	public WSLiveServicePortImpDelegate getWSLiveServicePortImpPort() {
		return super.getPort(new QName("http://ws.live.bbva.com/", "WSLiveServicePortImpPort"),
				WSLiveServicePortImpDelegate.class);
	}

}
