
package com.bbva.live.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSLiveServicePortImpDelegate", targetNamespace = "http://ws.live.bbva.com/")
public interface WSLiveServicePortImpDelegate {

	/**
	 * 
	 * @param documento
	 * @return returns com.bbva.live.ws.WsExpediente
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "enviaExpediente", targetNamespace = "http://ws.live.bbva.com/", className = "com.bbva.live.ws.EnviaExpediente")
	@ResponseWrapper(localName = "enviaExpedienteResponse", targetNamespace = "http://ws.live.bbva.com/", className = "com.bbva.live.ws.EnviaExpedienteResponse")
	public WsExpediente enviaExpediente(@WebParam(name = "documento", targetNamespace = "") DocumentoBean documento);

	/**
	 * 
	 * @param id
	 * @return returns byte[]
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDocumento", targetNamespace = "http://ws.live.bbva.com/", className = "com.bbva.live.ws.GetDocumento")
	@ResponseWrapper(localName = "getDocumentoResponse", targetNamespace = "http://ws.live.bbva.com/", className = "com.bbva.live.ws.GetDocumentoResponse")
	public byte[] getDocumento(@WebParam(name = "id", targetNamespace = "") String id);

}
