
package syc.bbva.app.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DigitalizacionServiceDelegate", targetNamespace = "http://ws.digitalizacion.bbva.syc/")
public interface DigitalizacionServiceDelegate {

	/**
	 * 
	 * @param genericFile
	 * @param listaCampos
	 * @param listaValores
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "servicioGlobal", targetNamespace = "http://ws.digitalizacion.bbva.syc/", className = "syc.bbva.digitalizacion.ws.ServicioGlobal")
	@ResponseWrapper(localName = "servicioGlobalResponse", targetNamespace = "http://ws.digitalizacion.bbva.syc/", className = "syc.bbva.digitalizacion.ws.ServicioGlobalResponse")
	public String servicioGlobal(@WebParam(name = "genericFile", targetNamespace = "") byte[] genericFile,
			@WebParam(name = "listaCampos", targetNamespace = "") String listaCampos,
			@WebParam(name = "listaValores", targetNamespace = "") String listaValores);

}
