//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package syc.bbva.gestorremoto.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "DigitalizacionServiceDelegate", targetNamespace = "http://ws.gestorRemoto.bbva.syc/")
public interface DigitalizacionServiceDelegate {

	/**
	 * 
	 * @param genericFile
	 * @param listaCampos
	 * @param listaValores
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "servicioGlobal", targetNamespace = "http://ws.gestorRemoto.bbva.syc/", className = "syc.bbva.gestorremoto.ws.ServicioGlobal")
	@ResponseWrapper(localName = "servicioGlobalResponse", targetNamespace = "http://ws.gestorRemoto.bbva.syc/", className = "syc.bbva.gestorremoto.ws.ServicioGlobalResponse")
	public String servicioGlobal(
			@WebParam(name = "genericFile", targetNamespace = "") byte[] genericFile,
			@WebParam(name = "listaCampos", targetNamespace = "") String listaCampos,
			@WebParam(name = "listaValores", targetNamespace = "") String listaValores);

}
