
package syc.bbva.firdig.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.bbva.firdig.configuracion.ConfWsFirma;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* DigitalizacionService service = new DigitalizacionService();
* DigitalizacionServiceDelegate portType = service.getDigitalizacionServicePort();
* portType.servicioGlobal(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "DigitalizacionService", targetNamespace = "http://ws.digitalizacion.bbva.syc/", wsdlLocation = "http://150.250.234.123:36081/LLFirmaDigital/DigitalizacionService/WEB-INF/wsdl/DigitalizacionService.wsdl")
public class DigitalizacionService extends Service {

	private final static URL DIGITALIZACIONSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(syc.bbva.firdig.ws.DigitalizacionService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = syc.bbva.firdig.ws.DigitalizacionService.class.getResource(".");
			url = new URL(baseUrl, ConfWsFirma.wsLLFirma[ConfWsFirma.entorno]);
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: '"+ConfWsFirma.wsLLFirma[ConfWsFirma.entorno]+"', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DIGITALIZACIONSERVICE_WSDL_LOCATION = url;
	}

	public DigitalizacionService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DigitalizacionService() {
		super(DIGITALIZACIONSERVICE_WSDL_LOCATION,
				new QName("http://ws.digitalizacion.bbva.syc/", "DigitalizacionService"));
	}

	/**
	 * 
	 * @return returns DigitalizacionServiceDelegate
	 */
	@WebEndpoint(name = "DigitalizacionServicePort")
	public DigitalizacionServiceDelegate getDigitalizacionServicePort() {
		return super.getPort(new QName("http://ws.digitalizacion.bbva.syc/", "DigitalizacionServicePort"),
				DigitalizacionServiceDelegate.class);
	}

}
