
package processmsd;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GetMsdAvaluos", targetNamespace = "http://processmsd")
public interface GetMsdAvaluos {

	/**
	 * 
	 * @param folioexpediente
	 * @param aplicacion
	 * @param tipoArchivo
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "deleteFileReturn", targetNamespace = "http://processmsd")
	@RequestWrapper(localName = "deleteFile", targetNamespace = "http://processmsd", className = "processmsd.DeleteFile")
	@ResponseWrapper(localName = "deleteFileResponse", targetNamespace = "http://processmsd", className = "processmsd.DeleteFileResponse")
	public String deleteFile(
			@WebParam(name = "FOLIOEXPEDIENTE", targetNamespace = "http://processmsd") String folioexpediente,
			@WebParam(name = "TipoArchivo", targetNamespace = "http://processmsd") String tipoArchivo,
			@WebParam(name = "Aplicacion", targetNamespace = "http://processmsd") String aplicacion);

	/**
	 * 
	 * @param extesion
	 * @param cadenabase64
	 * @param folioexpediente
	 * @param aplicacion
	 * @param tipoArchivo
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "addFileReturn", targetNamespace = "http://processmsd")
	@RequestWrapper(localName = "addFile", targetNamespace = "http://processmsd", className = "processmsd.AddFile")
	@ResponseWrapper(localName = "addFileResponse", targetNamespace = "http://processmsd", className = "processmsd.AddFileResponse")
	public String addFile(@WebParam(name = "CADENABASE64", targetNamespace = "http://processmsd") String cadenabase64,
			@WebParam(name = "FOLIOEXPEDIENTE", targetNamespace = "http://processmsd") String folioexpediente,
			@WebParam(name = "TipoArchivo", targetNamespace = "http://processmsd") String tipoArchivo,
			@WebParam(name = "Extesion", targetNamespace = "http://processmsd") String extesion,
			@WebParam(name = "Aplicacion", targetNamespace = "http://processmsd") String aplicacion);

	/**
	 * 
	 * @param folioexpediente
	 * @param aplicacion
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(name = "getListFolReturn", targetNamespace = "http://processmsd")
	@RequestWrapper(localName = "getListFol", targetNamespace = "http://processmsd", className = "processmsd.GetListFol")
	@ResponseWrapper(localName = "getListFolResponse", targetNamespace = "http://processmsd", className = "processmsd.GetListFolResponse")
	public List<String> getListFol(
			@WebParam(name = "FOLIOEXPEDIENTE", targetNamespace = "http://processmsd") String folioexpediente,
			@WebParam(name = "Aplicacion", targetNamespace = "http://processmsd") String aplicacion);

	/**
	 * 
	 * @param folioexpediente
	 * @param aplicacion
	 * @param tipoArchivo
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "downloadfileReturn", targetNamespace = "http://processmsd")
	@RequestWrapper(localName = "downloadfile", targetNamespace = "http://processmsd", className = "processmsd.Downloadfile")
	@ResponseWrapper(localName = "downloadfileResponse", targetNamespace = "http://processmsd", className = "processmsd.DownloadfileResponse")
	public String downloadfile(
			@WebParam(name = "FOLIOEXPEDIENTE", targetNamespace = "http://processmsd") String folioexpediente,
			@WebParam(name = "TipoArchivo", targetNamespace = "http://processmsd") String tipoArchivo,
			@WebParam(name = "Aplicacion", targetNamespace = "http://processmsd") String aplicacion);

}
