//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 01:38:16 PM CDT 
//


package syc.bbva.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DATOS_PRODUCTO" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CARATULA" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="DESC_PRODUCTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ID_PRODUCTO" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="NUM_CUENTA" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="TASA_INT" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SALDO_AVG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="TASA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="GAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="RECA" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *                             &lt;element name="CTE_LEG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ANEXO_GRAL" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RFC" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *                             &lt;element name="DESC_PRODUCTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ID_PRODUCTO" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="REGIMEN" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *                             &lt;element name="FECHA_LUGAR" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ANEXO_COMPLEMENTO" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NUM_CLIENTE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *                             &lt;element name="FECHA" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>normalizedString">
 *                                     &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="VERSION_FO" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CVE_DOCTO" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ANEXO_BEN" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BENEFICIARIO" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="NOMBRE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="PARENTESCO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="PORCENTAJE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ANEXO_COMISION" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="COMISION" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="MONTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="CLASULAS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CANAL_DISPOSICION" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datosproducto"
})
@XmlRootElement(name = "CONTRATO")
public class Context {

    @XmlElement(name = "DATOS_PRODUCTO")
    protected Context.DATOSPRODUCTO datosproducto;

    /**
     * Gets the value of the datosproducto property.
     * 
     * @return
     *     possible object is
     *     {@link Context.DATOSPRODUCTO }
     *     
     */
    public Context.DATOSPRODUCTO getDATOSPRODUCTO() {
        return datosproducto;
    }

    /**
     * Sets the value of the datosproducto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Context.DATOSPRODUCTO }
     *     
     */
    public void setDATOSPRODUCTO(Context.DATOSPRODUCTO value) {
        this.datosproducto = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CARATULA" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="DESC_PRODUCTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ID_PRODUCTO" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="NUM_CUENTA" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="TASA_INT" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="SALDO_AVG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="TASA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="GAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="RECA" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
     *                   &lt;element name="CTE_LEG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ANEXO_GRAL" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RFC" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
     *                   &lt;element name="DESC_PRODUCTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ID_PRODUCTO" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="REGIMEN" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
     *                   &lt;element name="FECHA_LUGAR" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ANEXO_COMPLEMENTO" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NUM_CLIENTE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
     *                   &lt;element name="FECHA" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>normalizedString">
     *                           &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="VERSION_FO" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="CVE_DOCTO" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ANEXO_BEN" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BENEFICIARIO" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="NOMBRE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="PARENTESCO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="PORCENTAJE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ANEXO_COMISION" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="COMISION" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="MONTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="CLASULAS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="CANAL_DISPOSICION" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "caratula",
        "anexogral",
        "anexocomplemento",
        "anexoben",
        "anexocomision"
    })
    public static class DATOSPRODUCTO {

        @XmlElement(name = "CARATULA")
        protected Context.DATOSPRODUCTO.CARATULA caratula;
        @XmlElement(name = "ANEXO_GRAL")
        protected Context.DATOSPRODUCTO.ANEXOGRAL anexogral;
        @XmlElement(name = "ANEXO_COMPLEMENTO")
        protected Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO anexocomplemento;
        @XmlElement(name = "ANEXO_BEN")
        protected Context.DATOSPRODUCTO.ANEXOBEN anexoben;
        @XmlElement(name = "ANEXO_COMISION")
        protected Context.DATOSPRODUCTO.ANEXOCOMISION anexocomision;

        /**
         * Gets the value of the caratula property.
         * 
         * @return
         *     possible object is
         *     {@link Context.DATOSPRODUCTO.CARATULA }
         *     
         */
        public Context.DATOSPRODUCTO.CARATULA getCARATULA() {
            return caratula;
        }

        /**
         * Sets the value of the caratula property.
         * 
         * @param value
         *     allowed object is
         *     {@link Context.DATOSPRODUCTO.CARATULA }
         *     
         */
        public void setCARATULA(Context.DATOSPRODUCTO.CARATULA value) {
            this.caratula = value;
        }

        /**
         * Gets the value of the anexogral property.
         * 
         * @return
         *     possible object is
         *     {@link Context.DATOSPRODUCTO.ANEXOGRAL }
         *     
         */
        public Context.DATOSPRODUCTO.ANEXOGRAL getANEXOGRAL() {
            return anexogral;
        }

        /**
         * Sets the value of the anexogral property.
         * 
         * @param value
         *     allowed object is
         *     {@link Context.DATOSPRODUCTO.ANEXOGRAL }
         *     
         */
        public void setANEXOGRAL(Context.DATOSPRODUCTO.ANEXOGRAL value) {
            this.anexogral = value;
        }

        /**
         * Gets the value of the anexocomplemento property.
         * 
         * @return
         *     possible object is
         *     {@link Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO }
         *     
         */
        public Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO getANEXOCOMPLEMENTO() {
            return anexocomplemento;
        }

        /**
         * Sets the value of the anexocomplemento property.
         * 
         * @param value
         *     allowed object is
         *     {@link Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO }
         *     
         */
        public void setANEXOCOMPLEMENTO(Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO value) {
            this.anexocomplemento = value;
        }

        /**
         * Gets the value of the anexoben property.
         * 
         * @return
         *     possible object is
         *     {@link Context.DATOSPRODUCTO.ANEXOBEN }
         *     
         */
        public Context.DATOSPRODUCTO.ANEXOBEN getANEXOBEN() {
            return anexoben;
        }

        /**
         * Sets the value of the anexoben property.
         * 
         * @param value
         *     allowed object is
         *     {@link Context.DATOSPRODUCTO.ANEXOBEN }
         *     
         */
        public void setANEXOBEN(Context.DATOSPRODUCTO.ANEXOBEN value) {
            this.anexoben = value;
        }

        /**
         * Gets the value of the anexocomision property.
         * 
         * @return
         *     possible object is
         *     {@link Context.DATOSPRODUCTO.ANEXOCOMISION }
         *     
         */
        public Context.DATOSPRODUCTO.ANEXOCOMISION getANEXOCOMISION() {
            return anexocomision;
        }

        /**
         * Sets the value of the anexocomision property.
         * 
         * @param value
         *     allowed object is
         *     {@link Context.DATOSPRODUCTO.ANEXOCOMISION }
         *     
         */
        public void setANEXOCOMISION(Context.DATOSPRODUCTO.ANEXOCOMISION value) {
            this.anexocomision = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BENEFICIARIO" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="NOMBRE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="PARENTESCO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="PORCENTAJE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "beneficiario"
        })
        public static class ANEXOBEN {

            @XmlElement(name = "BENEFICIARIO", required = true)
            protected List<Context.DATOSPRODUCTO.ANEXOBEN.BENEFICIARIO> beneficiario;

            /**
             * Gets the value of the beneficiario property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the beneficiario property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBENEFICIARIO().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Context.DATOSPRODUCTO.ANEXOBEN.BENEFICIARIO }
             * 
             * 
             */
            public List<Context.DATOSPRODUCTO.ANEXOBEN.BENEFICIARIO> getBENEFICIARIO() {
                if (beneficiario == null) {
                    beneficiario = new ArrayList<Context.DATOSPRODUCTO.ANEXOBEN.BENEFICIARIO>();
                }
                return this.beneficiario;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="NOMBRE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="PARENTESCO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="PORCENTAJE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "nombre",
                "parentesco",
                "porcentaje"
            })
            public static class BENEFICIARIO {

                @XmlElement(name = "NOMBRE")
                protected String nombre;
                @XmlElement(name = "PARENTESCO")
                protected String parentesco;
                @XmlElement(name = "PORCENTAJE")
                protected String porcentaje;

                /**
                 * Gets the value of the nombre property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNOMBRE() {
                    return nombre;
                }

                /**
                 * Sets the value of the nombre property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNOMBRE(String value) {
                    this.nombre = value;
                }

                /**
                 * Gets the value of the parentesco property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPARENTESCO() {
                    return parentesco;
                }

                /**
                 * Sets the value of the parentesco property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPARENTESCO(String value) {
                    this.parentesco = value;
                }

                /**
                 * Gets the value of the porcentaje property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPORCENTAJE() {
                    return porcentaje;
                }

                /**
                 * Sets the value of the porcentaje property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPORCENTAJE(String value) {
                    this.porcentaje = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="COMISION" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="MONTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="CLASULAS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="CANAL_DISPOSICION" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "comision",
            "canaldisposicion"
        })
        public static class ANEXOCOMISION {

            @XmlElement(name = "COMISION", required = true)
            protected List<Context.DATOSPRODUCTO.ANEXOCOMISION.COMISION> comision;
            @XmlElement(name = "CANAL_DISPOSICION", required = true)
            protected List<String> canaldisposicion;

            /**
             * Gets the value of the comision property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the comision property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCOMISION().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Context.DATOSPRODUCTO.ANEXOCOMISION.COMISION }
             * 
             * 
             */
            public List<Context.DATOSPRODUCTO.ANEXOCOMISION.COMISION> getCOMISION() {
                if (comision == null) {
                    comision = new ArrayList<Context.DATOSPRODUCTO.ANEXOCOMISION.COMISION>();
                }
                return this.comision;
            }

            /**
             * Gets the value of the canaldisposicion property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the canaldisposicion property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCANALDISPOSICION().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getCANALDISPOSICION() {
                if (canaldisposicion == null) {
                    canaldisposicion = new ArrayList<String>();
                }
                return this.canaldisposicion;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="MONTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="CLASULAS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "concepto",
                "monto",
                "clasulas"
            })
            public static class COMISION {

                @XmlElement(name = "CONCEPTO")
                protected String concepto;
                @XmlElement(name = "MONTO")
                protected String monto;
                @XmlElement(name = "CLASULAS")
                protected String clasulas;

                /**
                 * Gets the value of the concepto property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCONCEPTO() {
                    return concepto;
                }

                /**
                 * Sets the value of the concepto property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCONCEPTO(String value) {
                    this.concepto = value;
                }

                /**
                 * Gets the value of the monto property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMONTO() {
                    return monto;
                }

                /**
                 * Sets the value of the monto property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMONTO(String value) {
                    this.monto = value;
                }

                /**
                 * Gets the value of the clasulas property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCLASULAS() {
                    return clasulas;
                }

                /**
                 * Sets the value of the clasulas property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCLASULAS(String value) {
                    this.clasulas = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NUM_CLIENTE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
         *         &lt;element name="FECHA" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>normalizedString">
         *                 &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="VERSION_FO" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="CVE_DOCTO" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "numcliente",
            "version",
            "fecha",
            "versionfo",
            "cvedocto"
        })
        public static class ANEXOCOMPLEMENTO {

            @XmlElement(name = "NUM_CLIENTE")
            protected String numcliente;
            @XmlElement(name = "VERSION")
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            @XmlSchemaType(name = "normalizedString")
            protected String version;
            @XmlElement(name = "FECHA")
            protected Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.FECHA fecha;
            @XmlElement(name = "VERSION_FO")
            protected Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.VERSIONFO versionfo;
            @XmlElement(name = "CVE_DOCTO", type = Integer.class)
            protected List<Integer> cvedocto;

            /**
             * Gets the value of the numcliente property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public String getNUMCLIENTE() {
                return numcliente;
            }

            /**
             * Sets the value of the numcliente property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNUMCLIENTE(String value) {
                this.numcliente = value;
            }

            /**
             * Gets the value of the version property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVERSION() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVERSION(String value) {
                this.version = value;
            }

            /**
             * Gets the value of the fecha property.
             * 
             * @return
             *     possible object is
             *     {@link Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.FECHA }
             *     
             */
            public Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.FECHA getFECHA() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             * 
             * @param value
             *     allowed object is
             *     {@link Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.FECHA }
             *     
             */
            public void setFECHA(Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.FECHA value) {
                this.fecha = value;
            }

            /**
             * Gets the value of the versionfo property.
             * 
             * @return
             *     possible object is
             *     {@link Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.VERSIONFO }
             *     
             */
            public Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.VERSIONFO getVERSIONFO() {
                return versionfo;
            }

            /**
             * Sets the value of the versionfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.VERSIONFO }
             *     
             */
            public void setVERSIONFO(Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.VERSIONFO value) {
                this.versionfo = value;
            }

            /**
             * Gets the value of the cvedocto property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the cvedocto property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCVEDOCTO().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Integer }
             * 
             * 
             */
            public List<Integer> getCVEDOCTO() {
                if (cvedocto == null) {
                    cvedocto = new ArrayList<Integer>();
                }
                return this.cvedocto;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>normalizedString">
             *       &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class FECHA {

                @XmlValue
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected String value;
                @XmlAttribute(name = "constante", required = true)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected String constante;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the constante property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getConstante() {
                    return constante;
                }

                /**
                 * Sets the value of the constante property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setConstante(String value) {
                    this.constante = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class VERSIONFO {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "constante", required = true)
                protected boolean constante;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the constante property.
                 * 
                 */
                public boolean isConstante() {
                    return constante;
                }

                /**
                 * Sets the value of the constante property.
                 * 
                 */
                public void setConstante(boolean value) {
                    this.constante = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RFC" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
         *         &lt;element name="DESC_PRODUCTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ID_PRODUCTO" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="REGIMEN" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
         *         &lt;element name="FECHA_LUGAR" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rfc",
            "descproducto",
            "idproducto",
            "regimen",
            "fechalugar"
        })
        public static class ANEXOGRAL {

            @XmlElement(name = "RFC")
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            @XmlSchemaType(name = "normalizedString")
            protected String rfc;
            @XmlElement(name = "DESC_PRODUCTO")
            protected String descproducto;
            @XmlElement(name = "ID_PRODUCTO")
            protected Context.DATOSPRODUCTO.ANEXOGRAL.IDPRODUCTO idproducto;
            @XmlElement(name = "REGIMEN")
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            @XmlSchemaType(name = "normalizedString")
            protected String regimen;
            @XmlElement(name = "FECHA_LUGAR")
            protected Context.DATOSPRODUCTO.ANEXOGRAL.FECHALUGAR fechalugar;

            /**
             * Gets the value of the rfc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRFC() {
                return rfc;
            }

            /**
             * Sets the value of the rfc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRFC(String value) {
                this.rfc = value;
            }

            /**
             * Gets the value of the descproducto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDESCPRODUCTO() {
                return descproducto;
            }

            /**
             * Sets the value of the descproducto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDESCPRODUCTO(String value) {
                this.descproducto = value;
            }

            /**
             * Gets the value of the idproducto property.
             * 
             * @return
             *     possible object is
             *     {@link Context.DATOSPRODUCTO.ANEXOGRAL.IDPRODUCTO }
             *     
             */
            public Context.DATOSPRODUCTO.ANEXOGRAL.IDPRODUCTO getIDPRODUCTO() {
                return idproducto;
            }

            /**
             * Sets the value of the idproducto property.
             * 
             * @param value
             *     allowed object is
             *     {@link Context.DATOSPRODUCTO.ANEXOGRAL.IDPRODUCTO }
             *     
             */
            public void setIDPRODUCTO(Context.DATOSPRODUCTO.ANEXOGRAL.IDPRODUCTO value) {
                this.idproducto = value;
            }

            /**
             * Gets the value of the regimen property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getREGIMEN() {
                return regimen;
            }

            /**
             * Sets the value of the regimen property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setREGIMEN(String value) {
                this.regimen = value;
            }

            /**
             * Gets the value of the fechalugar property.
             * 
             * @return
             *     possible object is
             *     {@link Context.DATOSPRODUCTO.ANEXOGRAL.FECHALUGAR }
             *     
             */
            public Context.DATOSPRODUCTO.ANEXOGRAL.FECHALUGAR getFECHALUGAR() {
                return fechalugar;
            }

            /**
             * Sets the value of the fechalugar property.
             * 
             * @param value
             *     allowed object is
             *     {@link Context.DATOSPRODUCTO.ANEXOGRAL.FECHALUGAR }
             *     
             */
            public void setFECHALUGAR(Context.DATOSPRODUCTO.ANEXOGRAL.FECHALUGAR value) {
                this.fechalugar = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class FECHALUGAR {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "tipo", required = true)
                @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                @XmlSchemaType(name = "normalizedString")
                protected String tipo;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the tipo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTipo() {
                    return tipo;
                }

                /**
                 * Sets the value of the tipo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTipo(String value) {
                    this.tipo = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class IDPRODUCTO {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "constante", required = true)
                protected boolean constante;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the constante property.
                 * 
                 */
                public boolean isConstante() {
                    return constante;
                }

                /**
                 * Sets the value of the constante property.
                 * 
                 */
                public void setConstante(boolean value) {
                    this.constante = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DESC_PRODUCTO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ID_PRODUCTO" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="NUM_CUENTA" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="TASA_INT" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="SALDO_AVG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="TASA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="GAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="RECA" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
         *         &lt;element name="CTE_LEG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "descproducto",
            "idproducto",
            "numcuenta",
            "tasaint",
            "gat",
            "reca",
            "cteleg"
        })
        public static class CARATULA {

            @XmlElement(name = "DESC_PRODUCTO")
            protected String descproducto;
            @XmlElement(name = "ID_PRODUCTO")
            protected Context.DATOSPRODUCTO.CARATULA.IDPRODUCTO idproducto;
            @XmlElement(name = "NUM_CUENTA")
            protected Integer numcuenta;
            @XmlElement(name = "TASA_INT", required = true)
            protected List<Context.DATOSPRODUCTO.CARATULA.TASAINT> tasaint;
            @XmlElement(name = "GAT")
            protected String gat;
            @XmlElement(name = "RECA")
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            @XmlSchemaType(name = "normalizedString")
            protected String reca;
            @XmlElement(name = "CTE_LEG")
            protected String cteleg;

            /**
             * Gets the value of the descproducto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDESCPRODUCTO() {
                return descproducto;
            }

            /**
             * Sets the value of the descproducto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDESCPRODUCTO(String value) {
                this.descproducto = value;
            }

            /**
             * Gets the value of the idproducto property.
             * 
             * @return
             *     possible object is
             *     {@link Context.DATOSPRODUCTO.CARATULA.IDPRODUCTO }
             *     
             */
            public Context.DATOSPRODUCTO.CARATULA.IDPRODUCTO getIDPRODUCTO() {
                return idproducto;
            }

            /**
             * Sets the value of the idproducto property.
             * 
             * @param value
             *     allowed object is
             *     {@link Context.DATOSPRODUCTO.CARATULA.IDPRODUCTO }
             *     
             */
            public void setIDPRODUCTO(Context.DATOSPRODUCTO.CARATULA.IDPRODUCTO value) {
                this.idproducto = value;
            }

            /**
             * Gets the value of the numcuenta property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNUMCUENTA() {
                return numcuenta;
            }

            /**
             * Sets the value of the numcuenta property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNUMCUENTA(Integer value) {
                this.numcuenta = value;
            }

            /**
             * Gets the value of the tasaint property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tasaint property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTASAINT().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Context.DATOSPRODUCTO.CARATULA.TASAINT }
             * 
             * 
             */
            public List<Context.DATOSPRODUCTO.CARATULA.TASAINT> getTASAINT() {
                if (tasaint == null) {
                    tasaint = new ArrayList<Context.DATOSPRODUCTO.CARATULA.TASAINT>();
                }
                return this.tasaint;
            }

            /**
             * Gets the value of the gat property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGAT() {
                return gat;
            }

            /**
             * Sets the value of the gat property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGAT(String value) {
                this.gat = value;
            }

            /**
             * Gets the value of the reca property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRECA() {
                return reca;
            }

            /**
             * Sets the value of the reca property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRECA(String value) {
                this.reca = value;
            }

            /**
             * Gets the value of the cteleg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCTELEG() {
                return cteleg;
            }

            /**
             * Sets the value of the cteleg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCTELEG(String value) {
                this.cteleg = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="constante" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class IDPRODUCTO {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "constante", required = true)
                protected boolean constante;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the constante property.
                 * 
                 */
                public boolean isConstante() {
                    return constante;
                }

                /**
                 * Sets the value of the constante property.
                 * 
                 */
                public void setConstante(boolean value) {
                    this.constante = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="SALDO_AVG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="TASA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "saldoavg",
                "tasa"
            })
            public static class TASAINT {

                @XmlElement(name = "SALDO_AVG")
                protected String saldoavg;
                @XmlElement(name = "TASA")
                protected String tasa;

                /**
                 * Gets the value of the saldoavg property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSALDOAVG() {
                    return saldoavg;
                }

                /**
                 * Sets the value of the saldoavg property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSALDOAVG(String value) {
                    this.saldoavg = value;
                }

                /**
                 * Gets the value of the tasa property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTASA() {
                    return tasa;
                }

                /**
                 * Sets the value of the tasa property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTASA(String value) {
                    this.tasa = value;
                }

            }

        }

    }

}
