//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 01:38:16 PM CDT 
//


package syc.bbva.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

import syc.bbva.jaxb.Context;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bean.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bean.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.CARATULA }
     * 
     */
    public Context.DATOSPRODUCTO.CARATULA createContextDATOSPRODUCTOCARATULA() {
        return new Context.DATOSPRODUCTO.CARATULA();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.ANEXOCOMISION }
     * 
     */
    public Context.DATOSPRODUCTO.ANEXOCOMISION createContextDATOSPRODUCTOANEXOCOMISION() {
        return new Context.DATOSPRODUCTO.ANEXOCOMISION();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO }
     * 
     */
    public Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO createContextDATOSPRODUCTOANEXOCOMPLEMENTO() {
        return new Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.ANEXOGRAL }
     * 
     */
    public Context.DATOSPRODUCTO.ANEXOGRAL createContextDATOSPRODUCTOANEXOGRAL() {
        return new Context.DATOSPRODUCTO.ANEXOGRAL();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.CARATULA.TASAINT }
     * 
     */
    public Context.DATOSPRODUCTO.CARATULA.TASAINT createContextDATOSPRODUCTOCARATULATASAINT() {
        return new Context.DATOSPRODUCTO.CARATULA.TASAINT();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.ANEXOBEN }
     * 
     */
    public Context.DATOSPRODUCTO.ANEXOBEN createContextDATOSPRODUCTOANEXOBEN() {
        return new Context.DATOSPRODUCTO.ANEXOBEN();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.ANEXOBEN.BENEFICIARIO }
     * 
     */
    public Context.DATOSPRODUCTO.ANEXOBEN.BENEFICIARIO createContextDATOSPRODUCTOANEXOBENBENEFICIARIO() {
        return new Context.DATOSPRODUCTO.ANEXOBEN.BENEFICIARIO();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.CARATULA.IDPRODUCTO }
     * 
     */
    public Context.DATOSPRODUCTO.CARATULA.IDPRODUCTO createContextDATOSPRODUCTOCARATULAIDPRODUCTO() {
        return new Context.DATOSPRODUCTO.CARATULA.IDPRODUCTO();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.FECHA }
     * 
     */
    public Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.FECHA createContextDATOSPRODUCTOANEXOCOMPLEMENTOFECHA() {
        return new Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.FECHA();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.ANEXOGRAL.FECHALUGAR }
     * 
     */
    public Context.DATOSPRODUCTO.ANEXOGRAL.FECHALUGAR createContextDATOSPRODUCTOANEXOGRALFECHALUGAR() {
        return new Context.DATOSPRODUCTO.ANEXOGRAL.FECHALUGAR();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO }
     * 
     */
    public Context.DATOSPRODUCTO createContextDATOSPRODUCTO() {
        return new Context.DATOSPRODUCTO();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.VERSIONFO }
     * 
     */
    public Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.VERSIONFO createContextDATOSPRODUCTOANEXOCOMPLEMENTOVERSIONFO() {
        return new Context.DATOSPRODUCTO.ANEXOCOMPLEMENTO.VERSIONFO();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.ANEXOCOMISION.COMISION }
     * 
     */
    public Context.DATOSPRODUCTO.ANEXOCOMISION.COMISION createContextDATOSPRODUCTOANEXOCOMISIONCOMISION() {
        return new Context.DATOSPRODUCTO.ANEXOCOMISION.COMISION();
    }

    /**
     * Create an instance of {@link Context.DATOSPRODUCTO.ANEXOGRAL.IDPRODUCTO }
     * 
     */
    public Context.DATOSPRODUCTO.ANEXOGRAL.IDPRODUCTO createContextDATOSPRODUCTOANEXOGRALIDPRODUCTO() {
        return new Context.DATOSPRODUCTO.ANEXOGRAL.IDPRODUCTO();
    }

}
