//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package syc.bbva.firmadig.ws.cliente;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="envioArchivosBytesReturn" type="{http://ws.syc.com}ArrayOf_xsd_base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "envioArchivosBytesReturn" })
@XmlRootElement(name = "envioArchivosBytesResponse")
public class EnvioArchivosBytesResponse {

	@XmlElement(required = true, nillable = true)
	protected ArrayOfXsdBase64Binary envioArchivosBytesReturn;

	/**
	 * Gets the value of the envioArchivosBytesReturn property.
	 * 
	 * @return possible object is {@link ArrayOfXsdBase64Binary }
	 * 
	 */
	public ArrayOfXsdBase64Binary getEnvioArchivosBytesReturn() {
		return envioArchivosBytesReturn;
	}

	/**
	 * Sets the value of the envioArchivosBytesReturn property.
	 * 
	 * @param value
	 *            allowed object is {@link ArrayOfXsdBase64Binary }
	 * 
	 */
	public void setEnvioArchivosBytesReturn(ArrayOfXsdBase64Binary value) {
		this.envioArchivosBytesReturn = value;
	}

}
