//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package syc.bbva.firmadig.ws.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "WSExpunico_SEI", targetNamespace = "http://ws.syc.com")
public interface WSExpunicoSEI {

	/**
	 * @param arg21
	 * @param arg11
	 * @param arg01
	 * @return returns syc.bbva.firmadig.ws.cliente.ArrayOfXsdBase64Binary
	 */
	@WebMethod
	@WebResult(name = "envioArchivosBytesReturn", targetNamespace = "")
	@RequestWrapper(localName = "envioArchivosBytes", targetNamespace = "http://ws.syc.com", className = "syc.bbva.firmadig.ws.cliente.EnvioArchivosBytes")
	@ResponseWrapper(localName = "envioArchivosBytesResponse", targetNamespace = "http://ws.syc.com", className = "syc.bbva.firmadig.ws.cliente.EnvioArchivosBytesResponse")
	public ArrayOfXsdBase64Binary envioArchivosBytes(
			@WebParam(name = "arg_0_1", targetNamespace = "") String arg01,
			@WebParam(name = "arg_1_1", targetNamespace = "") String arg11,
			@WebParam(name = "arg_2_1", targetNamespace = "") String arg21);

	/**
	 * 
	 * @param arg20
	 * @param arg10
	 * @param arg00
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "obtenNumeroPaginasReturn", targetNamespace = "")
	@RequestWrapper(localName = "obtenNumeroPaginas", targetNamespace = "http://ws.syc.com", className = "syc.bbva.firmadig.ws.cliente.ObtenNumeroPaginas")
	@ResponseWrapper(localName = "obtenNumeroPaginasResponse", targetNamespace = "http://ws.syc.com", className = "syc.bbva.firmadig.ws.cliente.ObtenNumeroPaginasResponse")
	public String obtenNumeroPaginas(
			@WebParam(name = "arg_0_0", targetNamespace = "") String arg00,
			@WebParam(name = "arg_1_0", targetNamespace = "") String arg10,
			@WebParam(name = "arg_2_0", targetNamespace = "") String arg20);
	
	

	@WebMethod
	@WebResult(name = "envioArchivosReturn", targetNamespace = "")
	@RequestWrapper(localName = "envioArchivos", targetNamespace = "http://ws.syc.com", className = "syc.bbva.firmadig.ws.cliente.EnvioArchivos")
	@ResponseWrapper(localName = "envioArchivosResponse", targetNamespace = "http://ws.syc.com", className = "syc.bbva.firmadig.ws.cliente.EnvioArchivosResponse")
	public String envioArchivos(
			@WebParam(name = "arg_0_2", targetNamespace = "") String arg02,
			@WebParam(name = "arg_1_2", targetNamespace = "") String arg12,
			@WebParam(name = "arg_2_2", targetNamespace = "") String arg22,
			@WebParam(name = "arg_3_2", targetNamespace = "") byte[] arg32,
			@WebParam(name = "arg_4_2", targetNamespace = "") String arg42);

}
